-- MySQL Script generated by MySQL Workbench
-- Fri Nov  9 19:11:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydata
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydata` ;

-- -----------------------------------------------------
-- Schema mydata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydata` DEFAULT CHARACTER SET utf8 ;
USE `mydata` ;

-- -----------------------------------------------------
-- Table `mydata`.`re_tbl_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`re_tbl_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`re_tbl_board` (
  `bno` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `writer` VARCHAR(50) NULL DEFAULT NULL,
  `origin` INT(11) NULL DEFAULT '0',
  `depth` INT(11) NULL DEFAULT '0',
  `seq` INT(11) NULL DEFAULT '0',
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `viewcnt` INT(11) NULL DEFAULT '0',
  `uno` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`bno`),
  CONSTRAINT `fk_user_uno`
    FOREIGN KEY (`uno`)
    REFERENCES `mydata`.`tbl_user` (`uno`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_uno_idx` ON `mydata`.`re_tbl_board` (`uno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_attach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_attach` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_attach` (
  `fullname` VARCHAR(150) NOT NULL,
  `bno` INT(11) NOT NULL,
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fullname`),
  CONSTRAINT `fk_board_attach`
    FOREIGN KEY (`bno`)
    REFERENCES `mydata`.`re_tbl_board` (`bno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_board_attach` ON `mydata`.`tbl_attach` (`bno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_board` (
  `bno` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `writer` VARCHAR(45) NULL DEFAULT NULL,
  `regdate` TIMESTAMP NULL DEFAULT NULL,
  `viewcnt` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`bno`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_board_free`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_board_free` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_board_free` (
  `fno` INT(11) NOT NULL AUTO_INCREMENT,
  `ftitle` VARCHAR(50) NOT NULL,
  `fwriter` VARCHAR(50) NOT NULL,
  `fcontent` TEXT NULL DEFAULT NULL,
  `mcate` VARCHAR(20) NOT NULL,
  `fregdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fupdatedate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `origin` INT(11) NULL DEFAULT '0',
  `depth` INT(11) NULL DEFAULT '0',
  `seq` INT(11) NULL DEFAULT '0',
  `viewcnt` INT(11) NULL DEFAULT '0',
  `frecomcnt` INT(11) NULL DEFAULT '0',
  `mno` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`fno`),
  CONSTRAINT `fk_member_mno`
    FOREIGN KEY (`mno`)
    REFERENCES `mydata`.`tbl_member_book` (`mno`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_member_mno_idx` ON `mydata`.`tbl_board_free` (`mno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_board_t1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_board_t1` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_board_t1` (
  `bno` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` TEXT NOT NULL,
  `writer` VARCHAR(50) NOT NULL,
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `viewcnt` INT(11) NULL DEFAULT '0',
  `origin` INT(11) NULL DEFAULT '0',
  `depth` INT(11) NULL DEFAULT '0',
  `seq` INT(11) NULL DEFAULT '0',
  `thumupcnt` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`bno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_comment` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_comment` (
  `cno` INT(11) NOT NULL AUTO_INCREMENT,
  `bno` INT(11) NOT NULL,
  `commentText` VARCHAR(1000) NOT NULL,
  `commentAuth` VARCHAR(45) NOT NULL,
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `uno` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`cno`),
  CONSTRAINT `fk_board`
    FOREIGN KEY (`bno`)
    REFERENCES `mydata`.`re_tbl_board` (`bno`),
  CONSTRAINT `fk_tbl_user_uno`
    FOREIGN KEY (`uno`)
    REFERENCES `mydata`.`tbl_user` (`uno`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_board` ON `mydata`.`tbl_comment` (`bno` ASC) VISIBLE;

CREATE INDEX `fk_user_uno_idx` ON `mydata`.`tbl_comment` (`uno` ASC) VISIBLE;

CREATE INDEX `fk_tbl_user_uno_idx` ON `mydata`.`tbl_comment` (`uno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_member` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_member` (
  `userid` VARCHAR(50) NOT NULL,
  `userpw` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `regdate` DATE NULL DEFAULT NULL,
  `updatedate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_member_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_member_book` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_member_book` (
  `mno` INT(11) NOT NULL AUTO_INCREMENT,
  `mid` VARCHAR(30) NOT NULL,
  `mname` VARCHAR(30) NOT NULL,
  `memail` VARCHAR(60) NOT NULL,
  `mpassword` VARCHAR(60) NOT NULL,
  `mphone` VARCHAR(50) NOT NULL,
  `mbirth` INT(20) NOT NULL,
  `mgender` VARCHAR(20) NOT NULL,
  `mcate` VARCHAR(20) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mno`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_message` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_message` (
  `mno` INT(11) NOT NULL AUTO_INCREMENT,
  `targetid` VARCHAR(50) NOT NULL,
  `sender` VARCHAR(50) NOT NULL,
  `message` TEXT NOT NULL,
  `opendate` TIMESTAMP NULL DEFAULT NULL,
  `senddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mno`),
  CONSTRAINT `fk_usersender`
    FOREIGN KEY (`sender`)
    REFERENCES `mydata`.`tbl_user` (`uid`),
  CONSTRAINT `fk_usertarget`
    FOREIGN KEY (`targetid`)
    REFERENCES `mydata`.`tbl_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_usertarget` ON `mydata`.`tbl_message` (`targetid` ASC) VISIBLE;

CREATE INDEX `fk_usersender` ON `mydata`.`tbl_message` (`sender` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_user` (
  `uid` VARCHAR(50) NOT NULL,
  `upw` VARCHAR(50) NOT NULL,
  `uname` VARCHAR(100) NOT NULL,
  `upoint` INT(11) NOT NULL DEFAULT '0',
  `uno` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`uno`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `uid_UNIQUE` ON `mydata`.`tbl_user` (`uid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydata`.`test_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`test_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`test_board` (
  `bno` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `writer` VARCHAR(50) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `viewcnt` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`bno`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`test_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`test_member` ;

CREATE TABLE IF NOT EXISTS `mydata`.`test_member` (
  `userid` VARCHAR(50) NOT NULL,
  `userpw` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
